name: Debug

on:
  push:
    branches:
      - debug

jobs:
  # build-test:
  #   name: 'Build & test'
  #   runs-on: ubuntu-latest
  #   steps:
  #     # - name: Use Node.js
  #     #   uses: actions/setup-node@v5
  #     #   with:
  #     #     node-version: 16
  #     #     registry-url: 'https://registry.npmjs.org'
  #     #     always-auth: true
  #     - uses: actions/checkout@v4
  #       # these if statements ensure that a publication only occurs when
  #       # a new release is created:
  #     - run: yarn install
  #     - run: cd libs/sdk && yarn install
  #     # - run: yarn nx docs sdk
  deploy-static:
    name: Trigger static pages deploy
    runs-on: ubuntu-latest
    steps:
      - name: Trigger static pages deploy
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: pages.yml
