#
# Builds the docs and deploys to GitHub pages
#
# https://github.com/actions/setup-node
# Using https://github.com/marketplace/actions/deploy-to-github-pages

name: Deploy to Github pages
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  docs:
    name: Deploy to Github pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Yarn install
        run: yarn install --immutable --immutable-cache
      - name: Install SDK dependencies
        run: cd libs/sdk && yarn install
      - name: Build documentation
        run: yarn nx docs sdk
      - name: Deploy docs 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages # The branch the action should deploy to.
          folder: libs/sdk/static # The folder the action should deploy.
          clean: true # Automatically remove deleted files from the deploy branch
          commit-message: 'Deployed SDK Docs & Code Coverage to Github Pages (https://monerium.github.io/js-sdk)'
