#
# Builds the docs and deploys to GitHub pages
#
# https://github.com/actions/setup-node
# Using https://github.com/marketplace/actions/deploy-to-github-pages

name: Deploy to Github pages
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

jobs:
  docs:
    name: Deploy to Github pages
    runs-on: ubuntu-latest
    continue-on-error: true # while the SDK_GH_ACCESS_TOKEN is not approved
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: static-artifacts
      - name: Extract artifacts
        run: tar -xvf static.tar && mv static/* .
        shell: bash
      - name: Deploy docs 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          TOKEN: ${{ secrets.SDK_GH_ACCESS_TOKEN }}
          REPOSITORY-NAME: monerium/sdk
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: . # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
          COMMIT-MESSAGE: 'Deployed SDK Docs & Code Coverage to Github Pages (https://monerium.github.io/sdk)'
